baseURL = 'https://onionpsy.github.io/'
languageCode = 'en-us'
title = ''
theme = "cactus"

[params]
  colortheme = "classic"
  mainSection = "posts"
  mainSectionTitle = "Posts"
  showAllPostsOnHomePage = true
  showGallery = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
