baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Blog'
theme = "cactus"

[params]
  colortheme = "classic"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
